// 같은 실제 엔진으로 층 연결·차단·해치·보강·결정론을 검사합니다.
const assert=require('node:assert/strict'),fs=require('node:fs');const {fixture}=require('./qa-preparation-batch.cjs');
const root='../artifacts/draft-order-player-generator/src/domain/';
const {NAMSAN_MAP,layer,floorPoint}=require(root+'tacticalMaps.ts');
const {TacticalRealtimeSimulation,STAIR_SECONDS}=require(root+'realtime/TacticalRealtimeSimulation.ts');
const {resolveElectronicCounters}=require(root+'realtime/gadgetRules.ts');
const e=new TacticalRealtimeSimulation(),rows=[];const test=(name,fn)=>{fn();rows.push(name);console.log('PASS',name);};
test('두 층의 계단·해치 양쪽이 몸 반경으로 통행 가능',()=>{assert.equal(NAMSAN_MAP.floors.length,2);assert(NAMSAN_MAP.stairs.filter(s=>s.kind==='stair').length>=2);assert(NAMSAN_MAP.stairs.filter(s=>s.kind==='hatch').length>=2);for(const s of NAMSAN_MAP.stairs)for(const f of [0,1])assert(e.canStand(floorPoint(s.center,f),layer(NAMSAN_MAP,f)),s.id+' '+f);});
test('같은 평면 좌표의 두 층은 일반 관측·이동·EMP 차단',()=>{const a={position:floorPoint({x:1300,y:1260},1),floor:1,alive:true,facing:0};assert(!e.canObserve(a,{x:1310,y:1260},NAMSAN_MAP));assert(!e.canTraverse(a.position,{x:1300,y:1260,floor:0},NAMSAN_MAP));const devices=[{id:'camera',kind:'camera',position:a.position,floor:1,activeAt:0,until:30},{id:'emp',kind:'emp',position:{x:1300,y:1260},floor:0,activeAt:0,until:1,radius:300}];resolveElectronicCounters(devices,0,()=>true);assert.equal(devices[0].disabledUntil,undefined);});
function traveler(floor,position){return {id:'walker',side:'공격',callSign:'MEDVED',position:floorPoint(position,floor),floor,velocity:{x:0,y:0},facing:0,alive:true,action:'approach',goal:'층 이동',routeIndex:0,formationIndex:0,utility:{breach:1}};}
const member=fixture(1,0).attackers[0];
function traverse(unit,goal,map,seconds=8){const events=[],nodes=e.buildNavigationNodes(map),plans=new Map(),yielding=new Map(),blocked=new Map(),reservations=new Map();let arrival;for(let t=0;t<=seconds*10;t++){e.move(unit,goal,member,map,t/10,[unit],nodes,plans,yielding,blocked,event=>events.push(event),reservations);if(events.some(event=>event.goal==='floor-changed')){arrival=t/10;break;}}return {events,arrival};}
test('계단은 고정 시간 뒤 층이 바뀌고 해치는 아래로만 이동',()=>{const map={...NAMSAN_MAP,stairs:NAMSAN_MAP.stairs.map(s=>({...s,open:true}))};const stair=map.stairs[0],u=traveler(0,stair.center),r=traverse(u,floorPoint(stair.center,1),map);assert.equal(u.floor,1);assert.equal(r.arrival,STAIR_SECONDS.stair);const hatch=map.stairs[2],down=traveler(1,hatch.center);assert(traverse(down,floorPoint(hatch.center,0),map).arrival>=STAIR_SECONDS.hatch);const up=traveler(0,hatch.center),onlyHatch={...map,stairs:[hatch]};assert.equal(traverse(up,floorPoint(hatch.center,1),onlyHatch).arrival,undefined);});
test('연질 해치는 실제 개방 후 통과, 보강 해치는 MEDVED 장약 소비',()=>{for(const reinforced of [false,true]){const h={...NAMSAN_MAP.stairs[2],reinforced,open:false},map={...NAMSAN_MAP,stairs:[h]},u=traveler(1,h.center),r=traverse(u,floorPoint(h.center,0),map);assert(h.open);assert(r.events.some(event=>event.goal==='hatch-opened'));assert(r.arrival>=(reinforced?4:2)+STAIR_SECONDS.hatch);assert.equal(u.utility.breach,reinforced?0:1);}});
test('닫힌 해치 차단·열린 해치만 위→아래 관측 허용',()=>{const h={...NAMSAN_MAP.stairs[2],open:true},map={...NAMSAN_MAP,stairs:[h]},a={alive:true,floor:1,position:floorPoint(h.center,1),facing:0},b={x:h.center.x+20,y:h.center.y};assert(e.canObserve(a,b,map));assert(!e.canObserve({...a,position:b,floor:0,facing:Math.PI},floorPoint(h.center,1),map));assert(!e.canObserve(a,{x:h.center.x+100,y:h.center.y},map));});
test('팀 보강 자원 초과·잘못된 대상 거절 및 스냅샷 보존',()=>{const input=fixture(1,0);input.reinforcementIds=['hatch-a','hatch-b'];const session=e.createSession(input),first=session.step().snapshot;assert.equal(first.reinforcementRemaining,4);assert(first.fortifications.some(f=>f.wallId==='hatch-a'));assert.throws(()=>e.run({...input,reinforcementIds:Array(7).fill('hatch-a')}));assert.throws(()=>e.run({...input,reinforcementIds:['missing']}));});
test('상층 시작 수비와 실제 세션의 이동·관측·사격 일치',()=>{const input=fixture(41,0,5);input.maxSeconds=70;const result=e.run(input),session=e.createSession(input);while(!session.isComplete)session.step();assert.deepEqual(session.getResult(),result);assert(result.snapshots[0].units.some(u=>u.floor===1));const transitions=result.events.filter(event=>event.goal==='floor-changed');assert(transitions.length,'실제 경기 층 이동 발생');for(let i=0;i<result.snapshots.length;i++){const s=result.snapshots[i];for(const u of s.units){assert(e.canStand(u.position,layer(NAMSAN_MAP,u.floor??0)),u.callSign+' '+s.time+' '+JSON.stringify(u.position));if(u.floorTraversal)assert(!s.units.some(v=>v.id===u.id&&v.action==='fire'));if(i){const old=result.snapshots[i-1].units.find(v=>v.id===u.id);if(old.floor!==u.floor)assert(transitions.some(event=>event.actor===u.id&&event.time===s.time));}}}fs.writeFileSync('validation/vertical-round.json',JSON.stringify({transitions,winner:result.winner,reason:result.objective.reason,seconds:result.executionTime},null,2));});
fs.writeFileSync('validation/vertical-combat.json',JSON.stringify({passed:rows.length,tests:rows},null,2)+'\n');
